import React from 'react';
// MUI imports
import { Grid2, Tooltip, useMediaQuery } from '@mui/material';

// Hero section image import
import heroSectionImg from '../../assets/image/hero-section-image/background.png';
import TitleSection from './components/titleSection';
// Custom styles
import { hero_section_container, hero_section_image } from './style';

export default function HeroSection({ theme }) {
  const matchMdDown = useMediaQuery(theme.breakpoints.down('md'));

  return (
    <Grid2 container spacing={4} sx={hero_section_container}>
      <Grid2 size={{ xs: 12, md: 6 }} order={matchMdDown ? 2 : 1}>
        <TitleSection theme={theme} />
      </Grid2>
      <Grid2 size={{ xs: 12, md: 6 }} order={!matchMdDown ? 2 : 1} sx={hero_section_image(matchMdDown)}>
        <Tooltip title={'This photo generated by www.bing.com'} placement='top' arrow>
          <img src={heroSectionImg} alt='hero_section_img' />
        </Tooltip>
      </Grid2>
    </Grid2>
  );
}
