import React from 'react';
// MUI imports
import { Box, Tooltip, useMediaQuery } from '@mui/material';

// Hero section image import
import heroSectionImg from '../../assets/image/hero-section-image/background.png';
import TitleSection from './components/titleSection';

export default function HeroSection({ theme }) {
  const matchMdDown = useMediaQuery(theme.breakpoints.down('md'));

  return (
    <Box display='flex' flexDirection={matchMdDown ? 'column-reverse' : 'row'} justifyContent='space-between' alignItems='center'>
      <Box display='flex' flexDirection='column' width={matchMdDown ? '100%' : '50%'}>
        <TitleSection theme={theme} matchMdDown={matchMdDown} />
      </Box>
      <Box display='flex' justifyContent={matchMdDown ? 'center' : 'flex-end'} width={matchMdDown ? '100%' : '50%'}>
        <Tooltip title={'This photo generated by www.bing.com'} placement='top' arrow>
          <img src={heroSectionImg} alt='hero_section_img' style={{ width: '75%' }} />
        </Tooltip>
      </Box>
    </Box>
  );
}
